// Real PDF generator that replaces the .txt-with-PDF-extension fake from
// page.tsx. Uses jsPDF (Node-compatible, browser-compatible, generates a
// real PDF blob) so iOS Safari downloads it as a file instead of opening
// the print dialog — that was v3 §0's iOS PDF fix and the launch-prep
// doc's #1 verify item.
//
// Photos and the BVC "Primary Source Research Documentation" page land
// in later branches (feat/track-e-photo-attachments, BVC missions). LAANC
// and Part 107 fields are rendered conditionally so the same generator
// works once those columns get UI.

import { jsPDF } from "jspdf";
import { CHECKLIST_SECTIONS, type ChecklistItem } from "./checklist-data";

export interface FlightRecord {
  flightNumber: number;
  takeoffLoc: string;
  landingLoc: string;
  launchTime: string;
  landingTime: string;
  elapsedTime: string;
  batteryVoltage: string;
  notes: string;
}

export interface Photo {
  url: string;        // Cloudinary URL (or any https image URL)
  caption?: string;
  uploadedAt?: string;
}

export interface MissionPdfInput {
  missionNumber: string;
  timestamp: string;
  pilotName: string;
  location: string;
  aircraftType: string;
  rpCert: string;
  weather: {
    temperature?: string;
    wind?: string;
    precipitation?: string;
  };
  // Per-item completion. Boolean for checklist items, string for sub-fields
  // (we flatten subfields as `${itemId}_${subId}` per page.tsx convention).
  completed: Record<string, boolean | string>;
  flightRecords: FlightRecord[];
  // Optional v3-spec fields. Render only when present so the generator
  // stays useful before the UI captures them.
  laancAuthorizationNumber?: string;
  photos?: Photo[];
}

const PAGE_WIDTH = 612; // Letter, points
const PAGE_HEIGHT = 792;
const MARGIN = 48;
const CONTENT_WIDTH = PAGE_WIDTH - MARGIN * 2;
const FOOTER_RESERVE = 40;
const BOTTOM_LIMIT = PAGE_HEIGHT - FOOTER_RESERVE;

type Cursor = { y: number };

function ensureSpace(doc: jsPDF, cursor: Cursor, needed: number) {
  if (cursor.y + needed > BOTTOM_LIMIT) {
    addFooter(doc);
    doc.addPage();
    cursor.y = MARGIN;
  }
}

function addFooter(doc: jsPDF) {
  const totalPages = doc.getNumberOfPages();
  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(120);
    doc.text(
      "fly.witus.online — Generated by Fly WitUS. Complies with 14 CFR Part 107 record-keeping.",
      PAGE_WIDTH / 2,
      PAGE_HEIGHT - 24,
      { align: "center" },
    );
    doc.text(`Page ${i} of ${totalPages}`, PAGE_WIDTH - MARGIN, PAGE_HEIGHT - 24, {
      align: "right",
    });
    doc.setTextColor(0);
  }
}

function drawHeader(doc: jsPDF, cursor: Cursor, missionNumber: string, timestamp: string) {
  doc.setFontSize(20);
  doc.setFont("helvetica", "bold");
  doc.text("FLY WIT US", MARGIN, cursor.y + 18);

  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(80);
  doc.text("FAA Part 107 Pre-Flight Documentation", MARGIN, cursor.y + 32);
  doc.setTextColor(0);

  doc.setFontSize(9);
  doc.setTextColor(120);
  doc.text(`Mission ${missionNumber}`, PAGE_WIDTH - MARGIN, cursor.y + 18, { align: "right" });
  doc.text(formatTimestamp(timestamp), PAGE_WIDTH - MARGIN, cursor.y + 32, { align: "right" });
  doc.setTextColor(0);

  cursor.y += 44;
  doc.setDrawColor(200);
  doc.line(MARGIN, cursor.y, PAGE_WIDTH - MARGIN, cursor.y);
  cursor.y += 16;
}

function drawSectionTitle(doc: jsPDF, cursor: Cursor, title: string) {
  ensureSpace(doc, cursor, 28);
  doc.setFontSize(13);
  doc.setFont("helvetica", "bold");
  doc.text(title, MARGIN, cursor.y);
  cursor.y += 6;
  doc.setDrawColor(180);
  doc.line(MARGIN, cursor.y, PAGE_WIDTH - MARGIN, cursor.y);
  cursor.y += 12;
}

function drawKeyValueGrid(
  doc: jsPDF,
  cursor: Cursor,
  pairs: Array<[string, string | undefined]>,
) {
  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  const colWidth = CONTENT_WIDTH / 2;
  const rowHeight = 18;

  for (let i = 0; i < pairs.length; i += 2) {
    ensureSpace(doc, cursor, rowHeight);
    for (let col = 0; col < 2; col++) {
      const pair = pairs[i + col];
      if (!pair) continue;
      const x = MARGIN + col * colWidth;
      doc.setFont("helvetica", "bold");
      doc.text(`${pair[0]}:`, x, cursor.y);
      doc.setFont("helvetica", "normal");
      const labelWidth = doc.getTextWidth(`${pair[0]}: `);
      doc.text(pair[1] || "—", x + labelWidth, cursor.y, {
        maxWidth: colWidth - labelWidth - 8,
      });
    }
    cursor.y += rowHeight;
  }
}

function drawChecklistItem(
  doc: jsPDF,
  cursor: Cursor,
  item: ChecklistItem,
  completed: MissionPdfInput["completed"],
) {
  const value = completed[item.id];
  const isChecked = value === true || (typeof value === "string" && value.length > 0);
  const status = isChecked ? "[x]" : "[ ]";
  const required = item.required ? " *" : "";
  const line = `${status} ${item.label}${required}`;

  ensureSpace(doc, cursor, 14);
  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.text(line, MARGIN + 8, cursor.y, { maxWidth: CONTENT_WIDTH - 8 });
  cursor.y += 14;

  if (typeof value === "string" && value.length > 0 && item.type === "text") {
    ensureSpace(doc, cursor, 12);
    doc.setFontSize(9);
    doc.setTextColor(100);
    doc.text(`    "${value}"`, MARGIN + 16, cursor.y, { maxWidth: CONTENT_WIDTH - 16 });
    doc.setTextColor(0);
    cursor.y += 12;
  }

  if (item.subfields && isChecked) {
    for (const sub of item.subfields) {
      const subValue = completed[`${item.id}_${sub.id}`];
      if (subValue === undefined || subValue === "") continue;
      ensureSpace(doc, cursor, 12);
      doc.setFontSize(9);
      doc.setTextColor(100);
      doc.text(`    ${sub.label}: ${String(subValue)}`, MARGIN + 16, cursor.y);
      doc.setTextColor(0);
      cursor.y += 12;
    }
  }
}

function drawFlightRecord(doc: jsPDF, cursor: Cursor, flight: FlightRecord) {
  ensureSpace(doc, cursor, 90);
  doc.setFontSize(11);
  doc.setFont("helvetica", "bold");
  doc.text(`Flight ${flight.flightNumber}`, MARGIN + 8, cursor.y);
  cursor.y += 14;

  drawKeyValueGrid(doc, cursor, [
    ["Takeoff Loc", flight.takeoffLoc],
    ["Landing Loc", flight.landingLoc],
    ["Launch Time", flight.launchTime],
    ["Landing Time", flight.landingTime],
    ["Elapsed", flight.elapsedTime],
    ["Battery", flight.batteryVoltage],
  ]);

  if (flight.notes) {
    ensureSpace(doc, cursor, 24);
    doc.setFontSize(9);
    doc.setFont("helvetica", "bold");
    doc.text("Notes:", MARGIN + 8, cursor.y);
    doc.setFont("helvetica", "normal");
    cursor.y += 12;
    doc.text(flight.notes, MARGIN + 16, cursor.y, { maxWidth: CONTENT_WIDTH - 16 });
    cursor.y += 14;
  }
  cursor.y += 6;
}

function drawSignatureBlock(doc: jsPDF, cursor: Cursor) {
  ensureSpace(doc, cursor, 80);
  cursor.y += 10;
  doc.setDrawColor(150);
  doc.line(MARGIN, cursor.y, PAGE_WIDTH - MARGIN, cursor.y);
  cursor.y += 18;

  doc.setFontSize(10);
  doc.setFont("helvetica", "bold");
  doc.text("Pilot Certification", MARGIN, cursor.y);
  cursor.y += 14;

  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.text(
    "I certify the above pre-flight inspection was completed and the flight(s) were conducted in compliance with 14 CFR Part 107.",
    MARGIN,
    cursor.y,
    { maxWidth: CONTENT_WIDTH },
  );
  cursor.y += 22;

  doc.setFont("helvetica", "normal");
  doc.text("Signature:", MARGIN, cursor.y);
  doc.line(MARGIN + 56, cursor.y, MARGIN + 280, cursor.y);
  doc.text("Date:", MARGIN + 320, cursor.y);
  doc.line(MARGIN + 350, cursor.y, PAGE_WIDTH - MARGIN, cursor.y);
}

// Detect image format from a fetched blob's MIME type. jsPDF's addImage
// expects the format string ("JPEG", "PNG", "WEBP"). HEIC isn't supported
// by jsPDF — Cloudinary auto-converts on upload but we still guard.
function jsPdfFormatFor(mime: string): "JPEG" | "PNG" | "WEBP" | null {
  if (mime.includes("jpeg") || mime.includes("jpg")) return "JPEG";
  if (mime.includes("png")) return "PNG";
  if (mime.includes("webp")) return "WEBP";
  return null;
}

async function blobToDataUrl(blob: Blob): Promise<string> {
  return new Promise((resolve, reject) => {
    const reader = new FileReader();
    reader.onload = () => resolve(reader.result as string);
    reader.onerror = () => reject(reader.error);
    reader.readAsDataURL(blob);
  });
}

interface FetchedPhoto {
  caption?: string;
  dataUrl: string;
  format: "JPEG" | "PNG" | "WEBP";
  // Native pixel dimensions of the source image, used to preserve aspect ratio.
  pxWidth: number;
  pxHeight: number;
}

async function fetchPhoto(p: Photo): Promise<FetchedPhoto | null> {
  try {
    const res = await fetch(p.url, { signal: AbortSignal.timeout(10_000) });
    if (!res.ok) return null;
    const blob = await res.blob();
    const format = jsPdfFormatFor(blob.type);
    if (!format) return null;
    const dataUrl = await blobToDataUrl(blob);
    const dims = await readImageDimensions(dataUrl);
    if (!dims) return null;
    return { caption: p.caption, dataUrl, format, pxWidth: dims.w, pxHeight: dims.h };
  } catch {
    return null;
  }
}

function readImageDimensions(dataUrl: string): Promise<{ w: number; h: number } | null> {
  // We use the DOM Image API in the browser. Server-side rendering would
  // need a different path (e.g. an image-size lib) — but the PDF generator
  // only runs in the browser since downloadMissionPdf calls doc.save().
  if (typeof window === "undefined") return Promise.resolve(null);
  return new Promise((resolve) => {
    const img = new Image();
    img.onload = () => resolve({ w: img.naturalWidth, h: img.naturalHeight });
    img.onerror = () => resolve(null);
    img.src = dataUrl;
  });
}

function drawPhoto(doc: jsPDF, cursor: Cursor, photo: FetchedPhoto) {
  // Cap photo at 400pt wide; preserve aspect ratio.
  const maxWidth = Math.min(400, CONTENT_WIDTH - 16);
  const aspectRatio = photo.pxHeight / photo.pxWidth;
  const drawWidth = maxWidth;
  const drawHeight = Math.min(420, drawWidth * aspectRatio);
  const captionHeight = photo.caption ? 14 : 0;
  const totalHeight = drawHeight + captionHeight + 10;

  ensureSpace(doc, cursor, totalHeight);

  doc.addImage(photo.dataUrl, photo.format, MARGIN + 8, cursor.y, drawWidth, drawHeight);
  cursor.y += drawHeight + 4;

  if (photo.caption) {
    doc.setFontSize(9);
    doc.setFont("helvetica", "italic");
    doc.setTextColor(100);
    doc.text(photo.caption, MARGIN + 8, cursor.y, { maxWidth: drawWidth });
    doc.setTextColor(0);
    doc.setFont("helvetica", "normal");
    cursor.y += 14;
  }
  cursor.y += 6;
}

function drawPhotoUnavailable(doc: jsPDF, cursor: Cursor, p: Photo) {
  ensureSpace(doc, cursor, 18);
  doc.setFontSize(9);
  doc.setFont("helvetica", "italic");
  doc.setTextColor(160);
  doc.text(`[Photo unavailable: ${p.url}]`, MARGIN + 8, cursor.y, {
    maxWidth: CONTENT_WIDTH - 8,
  });
  doc.setTextColor(0);
  doc.setFont("helvetica", "normal");
  cursor.y += 16;
}

function formatTimestamp(iso: string): string {
  try {
    return new Date(iso).toLocaleString("en-US", {
      year: "numeric",
      month: "short",
      day: "numeric",
      hour: "2-digit",
      minute: "2-digit",
    });
  } catch {
    return iso;
  }
}

export async function generateMissionPdf(input: MissionPdfInput): Promise<jsPDF> {
  const doc = new jsPDF({ orientation: "portrait", unit: "pt", format: "letter" });
  const cursor: Cursor = { y: MARGIN };

  // Fetch photo data eagerly + in parallel so the PDF generation itself
  // stays a tight synchronous walk. Failed fetches surface as
  // "[Photo unavailable: <url>]" placeholders rather than aborting.
  const fetchedPhotos: Array<FetchedPhoto | null> = input.photos
    ? await Promise.all(input.photos.map(fetchPhoto))
    : [];

  drawHeader(doc, cursor, input.missionNumber, input.timestamp);

  drawSectionTitle(doc, cursor, "Mission Information");
  drawKeyValueGrid(doc, cursor, [
    ["Pilot", input.pilotName],
    ["RP Cert", input.rpCert],
    ["Location", input.location],
    ["Aircraft", input.aircraftType],
    ...(input.laancAuthorizationNumber
      ? ([["LAANC Auth #", input.laancAuthorizationNumber]] as Array<[string, string]>)
      : []),
  ]);
  cursor.y += 8;

  drawSectionTitle(doc, cursor, "Weather Conditions");
  drawKeyValueGrid(doc, cursor, [
    ["Temperature", input.weather.temperature],
    ["Wind", input.weather.wind],
    ["Precipitation", input.weather.precipitation],
  ]);
  cursor.y += 8;

  for (const section of CHECKLIST_SECTIONS) {
    drawSectionTitle(doc, cursor, section.title);
    for (const item of section.items) {
      drawChecklistItem(doc, cursor, item, input.completed);
    }
    cursor.y += 6;
  }

  if (input.flightRecords.length > 0) {
    drawSectionTitle(doc, cursor, "Flight Log");
    for (const flight of input.flightRecords) {
      drawFlightRecord(doc, cursor, flight);
    }
  }

  if (input.photos && input.photos.length > 0) {
    drawSectionTitle(doc, cursor, "Photos");
    input.photos.forEach((p, i) => {
      const fetched = fetchedPhotos[i];
      if (fetched) {
        drawPhoto(doc, cursor, fetched);
      } else {
        drawPhotoUnavailable(doc, cursor, p);
      }
    });
  }

  drawSignatureBlock(doc, cursor);

  // Footer numbering happens after all content is laid out so we know the
  // total page count.
  addFooter(doc);

  return doc;
}

export async function downloadMissionPdf(input: MissionPdfInput): Promise<void> {
  const doc = await generateMissionPdf(input);
  const safeMission = input.missionNumber.replace(/[^a-zA-Z0-9-_]/g, "_");
  doc.save(`fly-witus-mission-${safeMission}.pdf`);
}
